### ISSUE TITLE
docker: Error response from daemon: unknown or invalid runtime name: nvidia.

### ISSUE THREAD

**Issue by feiticeir0** [Seeed-Projects/jetson-examples#1]
You can probably run into the following error when running the examples:

```
Found compatible container dustynv/llava:r36.2.0 (2023-12-18, 8.0GB) - would you like to pull it? [Y/n] y
dustynv/llava:r36.2.0
+ docker run --runtime nvidia -it --rm --network host --volume /tmp/argus_socket:/tmp/argus_socket --volume /etc/enctune.conf:/etc/enctune.conf --volume /etc/nv_tegra_release:/etc/nv_tegra_release --volume /tmp/nv_jetson_model:/tmp/nv_jetson_model --volume /var/run/dbus:/var/run/dbus --volume /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket --volume /var/run/docker.sock:/var/run/docker.sock --volume /home/feiticeir0/reComputer/jetson-containers/data:/data --device /dev/snd --device /dev/bus/usb --device /dev/i2c-0 --device /dev/i2c-1 --device /dev/i2c-2 --device /dev/i2c-4 --device /dev/i2c-5 --device /dev/i2c-7 --device /dev/i2c-9 -v /run/jtop.sock:/run/jtop.sock dustynv/llava:r36.2.0 python3 -m llava.serve.cli --model-path liuhaotian/llava-v1.5-7b --image-file /data/images/hoover.jpg
**docker: Error response from daemon: unknown or invalid runtime name: nvidia.**
See 'docker run --help'.
----example done----
Only Support `run` or `clean` for now. try `reComputer run llava` .
```
You shoud state that the nvidia-container-toolkit must be installed and configured.
Here's the link for the instructions from the nvidia website:
[https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)

After installing it, all the examples should run

This is also an error when using dusty jetson-containers.

**Comment by yuyoujiang** [comment]
Hello feiticeir0, thank you very much for your feedback. You are right. If we want the container to run more consistently, we need to check the environment before running the container.

Perhaps we can refer here and edit the relevant actions into a script that runs automatically.
https://www.jetson-ai-lab.com/tips_ssd-docker.html

We're going to fix this, but until then, you'll need to manually configure the run environmen.
We also welcome the community to work together on this project, and Seeed may release a reward for this effort
😀.
https://github.com/orgs/Seeed-Studio/projects/6/views/1

**Comment by feiticeir0** [comment]
Hi @yuyoujiang  ! 
Thank you for the reply. I just opened this issue to alert for this.  Since this is using the dusty containers from NVIDIA, this issue also happens with theirs . 

> We also welcome the community to work together on this project, and Seeed may release a reward for this effort
> 😀.
> https://github.com/orgs/Seeed-Studio/projects/6/views/1

My name is already on this project - [https://github.com/orgs/Seeed-Studio/projects/6/views/1?pane=issue&itemId=64891723](https://github.com/orgs/Seeed-Studio/projects/6/views/1?pane=issue&itemId=64891723) - I'm that guy !

**Comment by yuyoujiang** [comment]
Hi @feiticeir0,  The device detection code has been updated(`/reComputer/script/utils.sh`), and it will help users automatically configure the runtime environment. Although there are some risks, it appears to be working fine at the moment.
