### ISSUE TITLE
ComfyUI not installing on Jetson Xavier AGX L4T VERSION 35.5.0

### ISSUE THREAD

**Issue by devrosx** [Seeed-Projects/jetson-examples#18]
Hello thanks for ComfyUI supportm but i have this error...
thanks Jan 

`0 upgraded, 0 newly installed, 0 to remove and 235 not upgraded.
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--explicit-start] [--explicit-end]
          [--in-place] [--version]
          [jq_filter] [files [files ...]]
yq: error: argument files: can't open './jetson-examples/reComputer/scripts/comfyui/config.yaml': [Errno 2] No such file or directory: './jetson-examples/reComputer/scripts/comfyui/config.yaml'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--explicit-start] [--explicit-end]
          [--in-place] [--version]
          [jq_filter] [files [files ...]]
yq: error: argument files: can't open './jetson-examples/reComputer/scripts/comfyui/config.yaml': [Errno 2] No such file or directory: './jetson-examples/reComputer/scripts/comfyui/config.yaml'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--explicit-start] [--explicit-end]
          [--in-place] [--version]
          [jq_filter] [files [files ...]]
yq: error: argument files: can't open './jetson-examples/reComputer/scripts/comfyui/config.yaml': [Errno 2] No such file or directory: './jetson-examples/reComputer/scripts/comfyui/config.yaml'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--explicit-start] [--explicit-end]
          [--in-place] [--version]
          [jq_filter] [files [files ...]]
yq: error: argument files: can't open './jetson-examples/reComputer/scripts/comfyui/config.yaml': [Errno 2] No such file or directory: './jetson-examples/reComputer/scripts/comfyui/config.yaml'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--explicit-start] [--explicit-end]
          [--in-place] [--version]
          [jq_filter] [files [files ...]]
yq: error: argument files: can't open './jetson-examples/reComputer/scripts/comfyui/config.yaml': [Errno 2] No such file or directory: './jetson-examples/reComputer/scripts/comfyui/config.yaml'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--explicit-start] [--explicit-end]
          [--in-place] [--version]
          [jq_filter] [files [files ...]]
yq: error: argument files: can't open './jetson-examples/reComputer/scripts/comfyui/config.yaml': [Errno 2] No such file or directory: './jetson-examples/reComputer/scripts/comfyui/config.yaml'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--explicit-start] [--explicit-end]
          [--in-place] [--version]
          [jq_filter] [files [files ...]]
yq: error: argument files: can't open './jetson-examples/reComputer/scripts/comfyui/config.yaml': [Errno 2] No such file or directory: './jetson-examples/reComputer/scripts/comfyui/config.yaml'
Allowed L4T versions:
Required disk space:  G
Minimum memory:  G
Minimum swap:  G
NVIDIA Jetson package:
Additional packages:
 is installed: OK!
L4T VERSION 35.5.0 is not in the allowed versions list.
An error occurred. Exiting...`

**Comment by devrosx** [comment]
when i clone manually to ./jetson-examples/reComputer/scripts/...
its not working because of this error
`update-alternatives: using /opt/nvidia/nsight-systems/2023.2.4/target-linux-tegra-armv8/nsys to provide /usr/local/bin/nsys (nsys) in auto mode
update-alternatives: using /opt/nvidia/nsight-systems/2023.2.4/host-linux-armv8/nsys-ui to provide /usr/local/bin/nsys-ui (nsys-ui) in auto mode
Setting up nvidia-jetpack-runtime (5.1.3-b29) ...
Setting up nvidia-nsight-sys (5.1.3-b29) ...
Setting up nvidia-jetpack-dev (5.1.3-b29) ...
Setting up nvidia-jetpack (5.1.3-b29) ...
Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
L4T VERSION 35.5.0 is not in the allowed versions list.
An error occurred. Exiting...`

checked my version its
jan@ubuntu:~$ head -n 1 /etc/nv_tegra_release
R35 (release), REVISION: 5.0, GCID: 35550185, BOARD: t186ref, EABI: aarch64, DATE: Tue Feb 20 04:46:31 UTC 2024
 35.5.0-20240219203809 


when i removed 
Check L4T version
Check memory and swap space (mine was 14 GB)
comfyui is installed ....
how can i change localhost url (its started with http://127.0.0.1:8188)?

**Comment by yuyoujiang** [comment]
Hello @devrosx , thank you for your feedback. This is a known issue, and we are working on resolving it. https://github.com/Seeed-Projects/jetson-examples/commit/9ffbfa7814e30d643cfa5c7e38d08f8b34edb6e5

You can skip the faulty device detection by commenting out the relevant section of the code, just like you're doing now. 💪

**Comment by yuyoujiang** [comment]
I'm not sure if the IP address in the URL can be changed, but you can modify the port number in the URL by:
1.changing the port mapping in Docker.
we can manually start the container using the following command.
```bash
    docker run -it --rm \
        --name $CONTAINER_NAME \
        --privileged \
        --network host \
        -p 8000:8188 \
        -v ~/ComfyUI:/usr/src/ComfyUI-Seeed \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v /dev/*:/dev/* \
        -v /etc/localtime:/etc/localtime:ro \
        --runtime nvidia \
        $IMAGE_NAME
```
now the url should be `http://127.0.0.1:8000/`
2.editing the confyui [configuration file](https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/cli_args.py)

**Comment by devrosx** [comment]
thanks, and if I want to set a parameter for ComfyUI main.py, where should I make adjustments? I apologize, I have never used Docker.
Tried to build ComfyUI manually, but I have problems with float8_e4m3fn error in flux models, Have you tried these models on the Jetson device?"
[https://forums.developer.nvidia.com/t/comfyui-error-float8-e4m3fn-with-pytorch/304812/3](url)

**Comment by yuyoujiang** [comment]
We can modify the contents of the `~/ComfyUI` directory, and the changes will be synced in real-time to the Docker container.
I haven't tried running these models yet, but this error seems to be related to dependency version issues. You can try installing the dependency versions recommended by ComfyUI.

**Comment by devrosx** [comment]
Yes I can modify contents, but how to run python3 main.py with arguments... 
with reComputer run comfyui it runs automatically with default setting
because now its runnig on http://127.0.0.1:8188 and its not visible on connected machine (works only in Jetson local browser)

**Comment by yuyoujiang** [comment]
I understand your requirements. This Docker container currently doesn't support editing the command to start `confyui`.
The [docker image](https://hub.docker.com/layers/yaohui1998/comfyui/latest/images/sha256-4681a82030890e1744f98a8a1aa1c1e5e3c31fb1bfc67ea1f62faf57a9355b46?context=explore) will eventually start confyui with the fixed command.

However, you can access the UI from other devices on the local network. You just need to change 127.0.0.1 to the IP address of the Jetson device on the local network. You can find the IP address of the Jetson device by entering the ifconfig command in the Jetson terminal.

If you still wish to modify the startup parameters for confyui, you can either recompile a new Docker container or directly change the default parameters in `main.py`.

**Comment by devrosx** [comment]
thanks, tried it with new docker container and it works...

Unfortunately, the error with float8_e4m3fn in Flux models is present in this build. It would be better to have a newer PyTorch (at least version 2.2) and compile it manually, because the latest version available on the Jetson website is 2.1.

**Comment by yuyoujiang** [comment]
Yes, if the precompiled package is not found, you will need to compile it manually.

**Comment by yuyoujiang** [comment]
I will temporarily close this issue, but you can reopen it at any time.
