### ISSUE TITLE
how to make a public link so I can test the software

### ISSUE THREAD

**Issue by tekntrash** [Seeed-Projects/jetson-examples#19]
Running  reComputer run yolov10 and it shows " To create a public link, set `share=True` in `launch()`", which is typical of gradio

Problem is that the thing is inside a docker, so I cannot just edit the "app.py" which runs the interface

And trying to run chrome or firefox on a jetson is a pain, so I really can't test the software

**Comment by yuyoujiang** [comment]
Hi @tekntrash , This is a major drawback of the project. You need to modify the code in YOLOv10 and then recompile the container you need, which can be a bit cumbersome.

Of course, there's a more convenient method:
1. Download the source code:
```
mkdir -p /home/$USER/reComputer
cd /home/$USER/reComputer
git clone https://github.com/THU-MIG/yolov10.git
```
2. Modify the source code.

3. Manually start the container and map the modified code into the container:
```
sudo docker run -it --rm --net=host --runtime nvidia \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /home/$USER/reComputer/yolov10:/opt/yolov10 \
    youjiang9977/yolov10-jetson:5.1.1
```
I haven't actually tested the above method, but you can give it a try.

**Comment by tekntrash** [comment]
I would suggest allowing to pass parameters for the reComputer command

something like "reComputer run blabla share=true ssh=yes" etc. basically, stuff related to gradio, which ultimately runs the thing

hope that helps, thanks for your answer and God bless

**Comment by tekntrash** [comment]
> Hi @tekntrash , This is a major drawback of the project. You need to modify the code in YOLOv10 and then recompile the container you need, which can be a bit cumbersome.
> 
> Of course, there's a more convenient method:
> 
>     1. Download the source code:
> 
> 
> ```
> mkdir -p /home/$USER/reComputer
> cd /home/$USER/reComputer
> git clone https://github.com/THU-MIG/yolov10.git
> ```
> 
>     2. Modify the source code.
> 
>     3. Manually start the container and map the modified code into the container:
> 
> 
> ```
> sudo docker run -it --rm --net=host --runtime nvidia \
>     -v /var/run/docker.sock:/var/run/docker.sock \
>     -v /home/$USER/reComputer/yolov10:/opt/yolov10 \
>     youjiang9977/yolov10-jetson:5.1.1
> ```
> 
> I haven't actually tested the above method, but you can give it a try.

it yields " FileNotFoundError: [Errno 2] No such file or directory: 'yolov10s.pt'" no matter what I do. too much work for something that was meant to be just a single command, thanks but will drop this

**Comment by yuyoujiang** [comment]
I can understand your needs, but implementing it with jetson-example requires more knowledge about using Docker. 
You can map the model's path to the inside of the container.

``` bash
sudo docker run -it --rm --net=host --runtime nvidia \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /home/$USER/reComputer/yolov10:/opt/yolov10 \
    -v /home/$USER/reComputer/yolov10/weights:/opt/yolov10/weights \
    -v /home/$USER/reComputer/yolov10/runs:/opt/yolov10/runs \
    youjiang9977/yolov10-jetson:5.1.1
```

Before starting the Docker container, you need to make sure that the file `yolov10s.pt` exists in the directory `/home/$USER/reComputer/yolov10/weights`.
