### ISSUE TITLE
如何让jetson nano b01科学上网 登上GitHub！！！

### ISSUE THREAD

**Issue by maomao725** [Seeed-Projects/jetson-examples#24]
试了好多办法都没法让jetson nano登上GitHub，求！急！谢谢大家

**Comment by maomao725** [comment]
How to get Jetson Nano B01 to access the internet scientifically and be uploaded to GitHub!

**Comment by yuyoujiang** [comment]
Hi @maomao725 , I'm sorry, I can't help you with this. Perhaps you could consider using a soft router to achieve it.
