### ISSUE TITLE
Updating ollama

### ISSUE THREAD

**Issue by ScissorSnips** [Seeed-Projects/jetson-examples#9]
To update ollama, do we need to wait for the dustynv jetsoncontainers to update the version? Or it can be updated otherwise?

**Comment by yuyoujiang** [comment]
Hi @GobbleSlop, can also update directly in jetsonexamples. 😀

**Comment by ScissorSnips** [comment]
Has anyone gotten this to work? The docs tell to run
curl -fsSL https://ollama.com/install.sh | sh

I try this inside the docker container on the jetson, but ollama --version still lists the old 0.1.43 version, not newer 0.3.4, even after reboot

**Comment by ScissorSnips** [comment]
I reached out to the original author of the docker image (I think?) and they said:

The original dockerfile I used to build the container that I think is still hosted on dustynv’s repo had built the ollama binary itself, it didn’t use the install shell script. That shell script probably won’t work as it’s geared to full installs with systemd running, not a container. 

If you clone the Jetson-containers repo and build the container with a new tag, that container should build to the latest Ollama version. 

Alternatively, you can clone the Ollama repo and follow their build instructions, their scripts should properly detect Jetson settings.

**Comment by yuyoujiang** [comment]
Yes, your idea is correct. If the Ollama version needs to be updated, a new Docker container must be compiled, and the environment within the container needs to be recompiled according to Ollama's requirements.

**Comment by ScissorSnips** [comment]
seeing https://github.com/dusty-nv/jetson-containers/issues/585
